--- #YAML:1.0
name:               WWW-Netflix-API
version:            0.05
abstract:           Interface for Netflix's API
author:
    - David Westbrook <dwestbrook@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:      0
    HTTP::Request::Common:  0
    LWP::Simple:          0
    LWP::UserAgent:       0
    Net::OAuth:           0
    Test::More:           0
    use URI::Escape:      0
    use WWW::Mechanize:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
