---
abstract: "Interface for Netflix's API"
author:
  - 'David Westbrook <dwestbrook@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Netflix-API
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  HTTP::Request::Common: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  Net::OAuth: 0.13
  Test::More: 0
  URI::Escape: 0
  WWW::Mechanize: 0
version: 0.12
